export interface Logo {
  id: number;
  name: string;
  acceptedAnswers: string[];
  fileName: string;
  hint: string;
}

const logoData: Logo[] = [
  {
    id: 1,
    name: "Singapore Airlines",
    acceptedAnswers: ["singapore airlines", "sq", "sia"],
    fileName: "uv8esrzjl3ntqnlmjs3n",
    hint: "Related to air travel.",
  },
  {
    id: 2,
    name: "Beyond the Vines",
    acceptedAnswers: ["beyond the vines", "beyondthevines", "btv"],
    fileName: "veu2casx2amr3iuoxhnf",
    hint: "Local design studio with multiple retail stores islandwide.",
  },
  {
    id: 3,
    name: "Development Bank of Singapore (DBS)",
    acceptedAnswers: ["dbs", "dbs bank", "development bank of singapore"],
    fileName: "hnnvqdv5foqai2grihrt",
    hint: "Bank known for its outages.",
  },
  {
    id: 4,
    name: "Carousell",
    acceptedAnswers: ["carousell", "carouhell"],
    fileName: "i2mcoudbbjmbyy5uuwbl",
    hint: "still avail??? hello???",
  },
  {
    id: 5,
    name: "Singapore Airport Terminal Services (SATS)",
    acceptedAnswers: ["sats", "singapore airport terminal services"],
    fileName: "woyg56eyqglyizb26y1t",
    hint: "Catering service provider.",
  },
  {
    id: 6,
    name: "Post Office Savings Bank (POSB)",
    acceptedAnswers: ["posb", "posb bank", "post office savings bank"],
    fileName: "pn2ai4dkkbc8mb8hxqc4",
    hint: "A local bank that got acquired in 1998.",
  },
  {
    id: 7,
    name: "Charles & Keith",
    acceptedAnswers: [
      "charles and keith",
      "charles & keith",
      "charles n keith",
      "charlesnkeith",
      "charlesandkeith",
    ],
    fileName: "ev2bwrl35rjk684poldm",
    hint: "Singaporean fashion house label with global presence.",
  },
  {
    id: 8,
    name: "Aftershock PC",
    acceptedAnswers: [
      "aftershock",
      "aftershock pc",
      "after shock",
      "after shock pc",
    ],
    fileName: "rt6crmluii9gku9vetpz",
    hint: "Custom-built PCs.",
  },
  {
    id: 9,
    name: "4FINGERS",
    acceptedAnswers: ["4fingers", "4 fingers", "four fingers"],
    fileName: "u2bbwtdouwwea7oqaxti",
    hint: "Fried chicken.",
  },
  {
    id: 10,
    name: "Creative Labs",
    acceptedAnswers: ["creative", "creative labs", "creative technology"],
    fileName: "vlrstsnxvoh1q3ntymvn",
    hint: "Local-based audio tech company.",
  },
  {
    id: 11,
    name: "Bengawan Solo",
    acceptedAnswers: ["bengawan solo", "bengawansolo"],
    fileName: "eymlbiixlajmynkwqg2i",
    hint: "Pandan chiffon cake.",
  },
  {
    id: 12,
    name: "Circles.Life",
    acceptedAnswers: ["circles.life", "circleslife", "circles life"],
    fileName: "ueme1pdjnvzfwip1fuzk",
    hint: "Singapore's fourth telco.",
  },
  {
    id: 13,
    name: "Eagle Brand",
    acceptedAnswers: ["eagle brand", "eaglebrand", "eagle"],
    fileName: "wfnek7jxf2cobvxs3fb2",
    hint: "Medicated oil.",
  },
  {
    id: 14,
    name: "Eu Yan Sang",
    acceptedAnswers: ["eu yan sang", "eu yan sang"],
    fileName: "am7sdsdsrp7t3qz8fbb7",
    hint: "Traditional chinese medicine.",
  },
  {
    id: 15,
    name: "Changi Jewel",
    acceptedAnswers: ["jewel", "changi jewel"],
    fileName: "fzliqzbuztglmgd0gbnz",
    hint: "Home to the world's largest and tallest indoor waterfall",
  },
  {
    id: 16,
    name: "Jumbo Seafood",
    acceptedAnswers: ["jumbo", "jumbo seafood"],
    fileName: "jex2cugfhei3xwvx5da8",
    hint: "Chilli crab.",
  },
  {
    id: 17,
    name: "Mediacorp",
    acceptedAnswers: ["mediacorp"],
    fileName: "fdwuvplpximowtgpbsyt",
    hint: "The one and only public broadcasting company in Singapore. 🌚",
  },
  {
    id: 18,
    name: "Camel Nuts",
    acceptedAnswers: ["camel", "camel nuts", "camelnuts"],
    fileName: "vzodddq5ta8j0mkay0ic",
    hint: "Self-explanatory.",
  },
  {
    id: 19,
    name: "M1",
    acceptedAnswers: ["m1", "m one", "mobile one", "mobileone"],
    fileName: "c8jkt6wfuxvcut07zyn8",
    hint: "One of the OG three major telcos in Singapore.",
  },
  {
    id: 20,
    name: "Love, Bonito",
    acceptedAnswers: ["love bonito", "lovebonito", "love, bonito"],
    fileName: "wiazoijlzk9ymamrc6rf",
    hint: "Local women fashion brand.",
  },
  {
    id: 21,
    name: "Ninja Van",
    acceptedAnswers: ["ninja van", "ninjavan"],
    fileName: "icwnb7pexkwixl6pb2ot",
    hint: 'Logistics "tech-enabled" start-up.',
  },
  {
    id: 22,
    name: "Mr Bean",
    acceptedAnswers: ["mr bean", "mr bean", "mister bean"],
    fileName: "pktd5a5uf8sunkzulckd",
    hint: "Soya milk.",
  },
  {
    id: 23,
    name: "NTUC Fairprice",
    acceptedAnswers: ["ntuc fairprice", "fairprice"],
    fileName: "kwniubfq0irixx1u8ruh",
    hint: 'Not to be confused with the "union".',
  },
  {
    id: 24,
    name: "OSIM",
    acceptedAnswers: ["osim"],
    fileName: "obeznns1gflyht6lyrou",
    hint: "Massage chairs.",
  },
  {
    id: 25,
    name: "Old Chang Kee",
    acceptedAnswers: ["old chang kee", "ock", "old changkee", "oldchangkee"],
    fileName: "hfwn5c3maiua4fonq870",
    hint: "Curry puffs.",
  },
  {
    id: 26,
    name: "OATSIDE",
    acceptedAnswers: ["oatside", "oat side"],
    fileName: "kaqr1vvdwmrhsefbncdb",
    hint: "Oat milk.",
  },
  {
    id: 27,
    name: "Killiney Kopitiam",
    acceptedAnswers: ["killiney", "killiney kopitiam"],
    fileName: "swwoyzfitt65nvvt2sso",
    hint: "Local coffeeshop chain.",
  },
  {
    id: 28,
    name: "IRVINS",
    acceptedAnswers: ["irvins", "irvin", "irvin's"],
    fileName: "b8xmvum2geqjz5s2zpst",
    hint: "Salted egg fish skin.",
  },
  {
    id: 29,
    name: "PastaMania",
    acceptedAnswers: ["pastamania", "pasta mania"],
    fileName: "jq9sifgrpcvlgeznldca",
    hint: "Pasta.",
  },
  {
    id: 30,
    name: "Razer",
    acceptedAnswers: ["razer"],
    fileName: "lcqqcru06nnzhxs0sfqu",
    hint: "Gaming peripherals.",
  },
  {
    id: 31,
    name: "Prima Taste",
    acceptedAnswers: ["prima taste", "primataste"],
    fileName: "zkx5kovqfl5zuet9lauv",
    hint: "Instant laksa.",
  },
  {
    id: 32,
    name: "Pearlie White",
    acceptedAnswers: ["pearlie white", "pearlie white"],
    fileName: "m6uxvycn0bb6x2ejnfbf",
    hint: "Oral care brand.",
  },
  {
    id: 33,
    name: "Singapore Exchange (SGX)",
    acceptedAnswers: ["sgx", "singapore exchange", "singaporeexchange"],
    fileName: "fkwbhwegmrxgfhdfexk0",
    hint: "Stock market.",
  },
  {
    id: 34,
    name: "RedMan (by Phoon Huat)",
    acceptedAnswers: [
      "redman",
      "red man",
      "phoon huat",
      "phoonhuat",
      "redmanshop",
    ],
    fileName: "vnfdwaovnrs2ncbcfb2z",
    hint: "Baking supplies.",
  },
  {
    id: 35,
    name: "Shopee",
    acceptedAnswers: ["shopee"],
    fileName: "k5odegdrdlsu54vip9va",
    hint: "Creator of the infamous Cristiano Ronaldo ad. 💀",
  },
  {
    id: 36,
    name: "Scoot",
    acceptedAnswers: ["scoot", "scoot airline", "scoot airlines"],
    fileName: "wtxsvvya956yxcx5kj76",
    hint: "Budget airline.",
  },
  {
    id: 37,
    name: "Singapore Pools",
    acceptedAnswers: ["singapore pools", "sgpools", "sg pools", "pools"],
    fileName: "b6iinzjjwavwhykpsrzf",
    hint: "4D, Toto.",
  },
  {
    id: 38,
    name: "StarHub",
    acceptedAnswers: ["starhub", "star hub"],
    fileName: "owvjhbmpapfhw0hgh2zq",
    hint: "One of the OG three major telcos in Singapore.",
  },
  {
    id: 39,
    name: "SingTel",
    acceptedAnswers: [
      "singtel",
      "sing tel",
      "singapore telecommunications",
      "singapore telecommunications limited",
    ],
    fileName: "vq9mf3zkjxajallyysc3",
    hint: "One of the OG three major telcos in Singapore.",
  },
  {
    id: 40,
    name: "Tiger Beer",
    acceptedAnswers: ["tiger beer", "tigerbeer"],
    fileName: "y1dcfpe09s6qbhzguxvr",
    hint: "Beer.",
  },
  {
    id: 41,
    name: "The Golden Duck Co.",
    acceptedAnswers: [
      "golden duck",
      "the golden duck",
      "goldenduck",
      "thegoldenduck",
      "the golden duck co.",
    ],
    fileName: "meyubw0kymii0zaxa5op",
    hint: "Salted egg yolk fish skin.",
  },
  {
    id: 42,
    name: "Udders",
    acceptedAnswers: ["udders"],
    fileName: "cphmafap57ry1yvw9zyi",
    hint: "Ice cream.",
  },
  {
    id: 43,
    name: "United Overseas Bank",
    acceptedAnswers: [
      "uob",
      "uob bank",
      "united overseas bank",
      "united overseas bank limited",
    ],
    fileName: "rhmwlngswjnk7cnzh7bo",
    hint: "Bank.",
  },
  {
    id: 44,
    name: "Tiger Balm",
    acceptedAnswers: ["tiger balm", "tigerbalm", "haw par healthcare"],
    fileName: "poeshuam630hou52c5bm",
    hint: "Analgesic heat rub.",
  },
  {
    id: 45,
    name: "Singapore Institute of Management (SIM)",
    acceptedAnswers: ["sim", "singapore institute of management"],
    fileName: "btxlgrbiesuqsaudzurz",
    hint: "Private university.",
  },
  {
    id: 46,
    name: "Singapore Institute of Technology (SIT)",
    acceptedAnswers: [
      "sit",
      "singaporetech",
      "singapore institute of technology",
    ],
    fileName: "lqopq5vz2frwqxso6mcp",
    hint: "One of the five public autonomous universities",
  },
  {
    id: 47,
    name: "Singapore University of Social Sciences (SUSS)",
    acceptedAnswers: ["suss", "singapore university of social sciences"],
    fileName: "by3m2nbmjyqsuqh6kkbs",
    hint: "One of the five public autonomous universities.",
  },
  {
    id: 48,
    name: "Singapore University of Technology and Design (SUTD)",
    acceptedAnswers: [
      "sutd",
      "singapore university of technology and design",
      "university of technology and design",
    ],
    fileName: "ctajjynbi6txxxhiqvhy",
    hint: "One of the five public autonomous universities",
  },
  {
    id: 49,
    name: "Singapore Management University (SMU)",
    acceptedAnswers: ["smu", "singapore management university"],
    fileName: "tc3ajrohma0t6y4mew51",
    hint: "One of the OG three public autonomous universities in Singapore.",
  },
  {
    id: 50,
    name: "Nanyang Technological University (NTU)",
    acceptedAnswers: ["ntu", "nanyang technological university"],
    fileName: "o9enaks5iklqz8qlgahj",
    hint: "One of the OG three public autonomous universities of Singapore.",
  },
  {
    id: 51,
    name: "National University of Singapore (NUS)",
    acceptedAnswers: ["nus", "national university of singapore"],
    fileName: "jk38lvy49gh5jdfdrjdc",
    hint: "One of the OG three public autonomous universities of Singapore.",
  },
  {
    id: 52,
    name: "Institute of Technical Education (ITE)",
    acceptedAnswers: ["ite", "institute of technical education"],
    fileName: "nrtbwdz1is9gvacw10rm",
    hint: "Nitec.",
  },
  {
    id: 53,
    name: "By Invite Only",
    acceptedAnswers: ["by invite only", "byinviteonly"],
    fileName: "qzhhcogd7epqfws1i8oh",
    hint: "Jewellery.",
  },
  {
    id: 54,
    name: "Singlife",
    acceptedAnswers: ["singlife", "sing life"],
    fileName: "ddjmzovx4mgob2wbduas",
    hint: "Insurance company.",
  },
  {
    id: 55,
    name: "Grab",
    acceptedAnswers: ["grab", "grab holdings"],
    fileName: "bad5dqfcj9dbcromcta3",
    hint: "Acquired Uber Southeast Asia in 2018.",
  },
  {
    id: 56,
    name: "Ya Kun Kaya Toast",
    acceptedAnswers: [
      "ya kun",
      "yakun",
      "ya kun kaya toast",
      "yakun kaya toast",
    ],
    fileName: "tqfbsutgtxra6ao408tt",
    hint: "Famous kaya toast.",
  },
  {
    id: 57,
    name: "Curious Creatures",
    acceptedAnswers: ["curious creatures", "curiouscreatures"],
    fileName: "ftfnzy8ncxbnd4g0q5ag",
    hint: "Jewellery.",
  },
  {
    id: 58,
    name: "KYDRA",
    acceptedAnswers: ["kydra", "kydra activewear"],
    fileName: "gh95acunypt3fhqrvujr",
    hint: "Activewear.",
  },
  {
    id: 59,
    name: "Bee Cheng Hiang",
    acceptedAnswers: ["bee cheng hiang", "beechenghiang"],
    fileName: "covby53ae5ug03lgwnx8",
    hint: "Ba Kwa.",
  },
  {
    id: 60,
    name: "The Soup Spoon",
    acceptedAnswers: [
      "soup spoon",
      "the soup spoon",
      "soupspoon",
      "thesoupspoon",
    ],
    fileName: "wqxtgvfvihckxfobjnro",
    hint: "Restaurant chain that sells soups.",
  },
  {
    id: 61,
    name: "LiHO Tea",
    acceptedAnswers: [
      "liho",
      "liho tea",
      "li ho",
      "li ho tea",
      "liho bubble tea",
      "li ho bubble tea",
    ],
    fileName: "n5p0zg4nybtpk5ozbdrl",
    hint: "Bubble tea.",
  },
  {
    id: 62,
    name: "DoDo",
    acceptedAnswers: ["dodo", "dodo fishball", "dodofishball"],
    fileName: "cnp1n8cuke5vxxytnlnh",
    hint: "Fishballs.",
  },
  {
    id: 63,
    name: "The SOS Kitchen",
    acceptedAnswers: [
      "sos",
      "the sos kitchen",
      "thesoskitchen",
      "sos kitchen",
      "soskitchen",
      "the soskitchen",
    ],
    fileName: "wdin4n9rdgbpz5lz810o",
    hint: "Sauces.",
  },
  {
    id: 64,
    name: "The Paper Bunny",
    acceptedAnswers: [
      "the paper bunny",
      "paper bunny",
      "thepaperbunny",
      "paperbunny",
      "the paperbunny",
    ],
    fileName: "uhuuqjx5yp4cf7ug3kil",
    hint: "Women's fashion brand.",
  },
  {
    id: 65,
    name: "The Tinsel Rack",
    acceptedAnswers: [
      "the tinsel rack",
      "thetinselrack",
      "tinsel rack",
      "tinselrack",
      "the tinselrack",
    ],
    fileName: "zv5khngv3ezzlurgspz4",
    hint: "Women's fashion brand.",
  },
  {
    id: 66,
    name: "Suria",
    acceptedAnswers: ["suria", "suria channel"],
    fileName: "qc3ehxzioeiqubqpni6z",
    hint: "Television channel.",
  },
  {
    id: 67,
    name: "Vasantham",
    acceptedAnswers: ["vasantham", "vasantham channel", "vasantham central"],
    fileName: "kazy0gkmuhwg3ygayhpg",
    hint: "Television channel.",
  },
  {
    id: 68,
    name: "Go-Ahead Singapore",
    acceptedAnswers: [
      "go-ahead singapore",
      "go-ahead",
      "go ahead singapore",
      "goahead singapore",
      "go ahead",
    ],
    fileName: "f7fuvdej4ak02bhbpbn0",
    hint: "Public transport operator.",
  },
  {
    id: 69,
    name: "SMRT Trains",
    acceptedAnswers: [
      "smrt",
      "smrt trains",
      "smrt limited",
      "singapore mrt",
      "smrt corporation",
    ],
    fileName: "i33qotjfme6ezaafgden",
    hint: "Public transport operator.",
  },
  {
    id: 70,
    name: "SBS Transit",
    acceptedAnswers: [
      "sbs",
      "sbs transit",
      "sbstransit",
      "singapore bus services",
    ],
    fileName: "s6qkte3fyzdzkndpytn9",
    hint: "Public transport operator.",
  },
  {
    id: 71,
    name: "Channel 8",
    acceptedAnswers: ["channel 8", "channel8", "channel eight"],
    fileName: "o79nja28jugknxynj9jh",
    hint: "Television channel.",
  },
  {
    id: 72,
    name: "Channel 5",
    acceptedAnswers: ["channel 5", "channel5", "channel five"],
    fileName: "bfqvmn5woainqmgmlp3p",
    hint: "Television channel.",
  },
  {
    id: 73,
    name: "Mothership",
    acceptedAnswers: ["mothership", "mother ship", "mothership.sg"],
    fileName: "ymgwxg9a12qomldxhpy9",
    hint: "Media company that got its press accreditation suspended twice in less than two years for breaking embargoes.",
  },
  {
    id: 74,
    name: "ShopBack",
    acceptedAnswers: ["shopback", "shop back", "shopback.sg"],
    fileName: "mqutiu7fhswbkvvmq5qk",
    hint: "Local tech startup that laid off 24% of employees in 2024.",
  },
];

export const getRandomLogos = (num: number) => {
  return logoData.sort(() => 0.5 - Math.random()).slice(0, num);
}